// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

/*
Package Report is a generated protocol buffer package.

It is generated from these files:
	control.proto
	data.proto
	manage.proto
	param.proto
	plc_status.proto

It has these top-level messages:
	ControlCommand
	Monitor
	Alter
	DataCommand
	ManageCommand
	Param
	PLCStataus
*/
package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControlCommand_CommandType int32

const (
	ControlCommand_CMT_INVALID                              ControlCommand_CommandType = 0
	ControlCommand_CMT_REQ_RESTART                          ControlCommand_CommandType = 3
	ControlCommand_CMT_REP_RESTART                          ControlCommand_CommandType = 32771
	ControlCommand_CMT_REQ_DATA_DOWNLOAD                    ControlCommand_CommandType = 7
	ControlCommand_CMT_REP_DATA_DOWNLOAD                    ControlCommand_CommandType = 32775
	ControlCommand_CMT_REQ_DATA_QUERY                       ControlCommand_CommandType = 8
	ControlCommand_CMT_REP_DATA_QUERY                       ControlCommand_CommandType = 32776
	ControlCommand_CMT_REQ_BATCH_ADD_MONITOR                ControlCommand_CommandType = 9
	ControlCommand_CMT_REP_BATCH_ADD_MONITOR                ControlCommand_CommandType = 32777
	ControlCommand_CMT_REQ_BATCH_ADD_ALTER                  ControlCommand_CommandType = 10
	ControlCommand_CMT_REP_BATCH_ADD_ALTER                  ControlCommand_CommandType = 32778
	ControlCommand_CMT_REQ_RS232_GET_CONFIG                 ControlCommand_CommandType = 17
	ControlCommand_CMT_REP_RS232_GET_CONFIG                 ControlCommand_CommandType = 32785
	ControlCommand_CMT_REQ_RS232_SET_CONFIG                 ControlCommand_CommandType = 18
	ControlCommand_CMT_REP_RS232_SET_CONFIG                 ControlCommand_CommandType = 32786
	ControlCommand_CMT_REQ_GET_PARAMTERS                    ControlCommand_CommandType = 19
	ControlCommand_CMT_REP_GET_PARAMTERS                    ControlCommand_CommandType = 32787
	ControlCommand_CMT_REQ_SET_PARAMTERS                    ControlCommand_CommandType = 20
	ControlCommand_CMT_REP_SET_PARAMTERS                    ControlCommand_CommandType = 32788
	ControlCommand_CMT_REQ_RS485_GET_CONFIG                 ControlCommand_CommandType = 33
	ControlCommand_CMT_REP_RS485_GET_CONFIG                 ControlCommand_CommandType = 32801
	ControlCommand_CMT_REQ_RS485_SET_CONFIG                 ControlCommand_CommandType = 34
	ControlCommand_CMT_REP_RS485_SET_CONFIG                 ControlCommand_CommandType = 32802
	ControlCommand_CMT_REQ_GET_SERVER_ADDR                  ControlCommand_CommandType = 4
	ControlCommand_CMT_REP_GET_SERVER_ADDR                  ControlCommand_CommandType = 32772
	ControlCommand_CMT_REQ_SET_SERVER_ADDR                  ControlCommand_CommandType = 5
	ControlCommand_CMT_REP_SET_SERVER_ADDR                  ControlCommand_CommandType = 32773
	ControlCommand_CMT_REQ_TRANSPARENT_TRANSMISSION         ControlCommand_CommandType = 21
	ControlCommand_CMT_REP_TRANSPARENT_TRANSMISSION         ControlCommand_CommandType = 32789
	ControlCommand_CMT_REQ_RELEASE_TRANSPARENT_TRANSMISSION ControlCommand_CommandType = 22
	ControlCommand_CMT_REP_RELEASE_TRANSPARENT_TRANSMISSION ControlCommand_CommandType = 32790
	ControlCommand_CMT_REQ_QUERY_ROUTER_STATUS              ControlCommand_CommandType = 256
	ControlCommand_CMT_REP_QUERY_ROUTER_STATUS              ControlCommand_CommandType = 33024
)

var ControlCommand_CommandType_name = map[int32]string{
	0:     "CMT_INVALID",
	3:     "CMT_REQ_RESTART",
	32771: "CMT_REP_RESTART",
	7:     "CMT_REQ_DATA_DOWNLOAD",
	32775: "CMT_REP_DATA_DOWNLOAD",
	8:     "CMT_REQ_DATA_QUERY",
	32776: "CMT_REP_DATA_QUERY",
	9:     "CMT_REQ_BATCH_ADD_MONITOR",
	32777: "CMT_REP_BATCH_ADD_MONITOR",
	10:    "CMT_REQ_BATCH_ADD_ALTER",
	32778: "CMT_REP_BATCH_ADD_ALTER",
	17:    "CMT_REQ_RS232_GET_CONFIG",
	32785: "CMT_REP_RS232_GET_CONFIG",
	18:    "CMT_REQ_RS232_SET_CONFIG",
	32786: "CMT_REP_RS232_SET_CONFIG",
	19:    "CMT_REQ_GET_PARAMTERS",
	32787: "CMT_REP_GET_PARAMTERS",
	20:    "CMT_REQ_SET_PARAMTERS",
	32788: "CMT_REP_SET_PARAMTERS",
	33:    "CMT_REQ_RS485_GET_CONFIG",
	32801: "CMT_REP_RS485_GET_CONFIG",
	34:    "CMT_REQ_RS485_SET_CONFIG",
	32802: "CMT_REP_RS485_SET_CONFIG",
	4:     "CMT_REQ_GET_SERVER_ADDR",
	32772: "CMT_REP_GET_SERVER_ADDR",
	5:     "CMT_REQ_SET_SERVER_ADDR",
	32773: "CMT_REP_SET_SERVER_ADDR",
	21:    "CMT_REQ_TRANSPARENT_TRANSMISSION",
	32789: "CMT_REP_TRANSPARENT_TRANSMISSION",
	22:    "CMT_REQ_RELEASE_TRANSPARENT_TRANSMISSION",
	32790: "CMT_REP_RELEASE_TRANSPARENT_TRANSMISSION",
	256:   "CMT_REQ_QUERY_ROUTER_STATUS",
	33024: "CMT_REP_QUERY_ROUTER_STATUS",
}
var ControlCommand_CommandType_value = map[string]int32{
	"CMT_INVALID":                              0,
	"CMT_REQ_RESTART":                          3,
	"CMT_REP_RESTART":                          32771,
	"CMT_REQ_DATA_DOWNLOAD":                    7,
	"CMT_REP_DATA_DOWNLOAD":                    32775,
	"CMT_REQ_DATA_QUERY":                       8,
	"CMT_REP_DATA_QUERY":                       32776,
	"CMT_REQ_BATCH_ADD_MONITOR":                9,
	"CMT_REP_BATCH_ADD_MONITOR":                32777,
	"CMT_REQ_BATCH_ADD_ALTER":                  10,
	"CMT_REP_BATCH_ADD_ALTER":                  32778,
	"CMT_REQ_RS232_GET_CONFIG":                 17,
	"CMT_REP_RS232_GET_CONFIG":                 32785,
	"CMT_REQ_RS232_SET_CONFIG":                 18,
	"CMT_REP_RS232_SET_CONFIG":                 32786,
	"CMT_REQ_GET_PARAMTERS":                    19,
	"CMT_REP_GET_PARAMTERS":                    32787,
	"CMT_REQ_SET_PARAMTERS":                    20,
	"CMT_REP_SET_PARAMTERS":                    32788,
	"CMT_REQ_RS485_GET_CONFIG":                 33,
	"CMT_REP_RS485_GET_CONFIG":                 32801,
	"CMT_REQ_RS485_SET_CONFIG":                 34,
	"CMT_REP_RS485_SET_CONFIG":                 32802,
	"CMT_REQ_GET_SERVER_ADDR":                  4,
	"CMT_REP_GET_SERVER_ADDR":                  32772,
	"CMT_REQ_SET_SERVER_ADDR":                  5,
	"CMT_REP_SET_SERVER_ADDR":                  32773,
	"CMT_REQ_TRANSPARENT_TRANSMISSION":         21,
	"CMT_REP_TRANSPARENT_TRANSMISSION":         32789,
	"CMT_REQ_RELEASE_TRANSPARENT_TRANSMISSION": 22,
	"CMT_REP_RELEASE_TRANSPARENT_TRANSMISSION": 32790,
	"CMT_REQ_QUERY_ROUTER_STATUS":              256,
	"CMT_REP_QUERY_ROUTER_STATUS":              33024,
}

func (x ControlCommand_CommandType) String() string {
	return proto.EnumName(ControlCommand_CommandType_name, int32(x))
}
func (ControlCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ControlCommand struct {
	Uuid         string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Tid          uint64                     `protobuf:"varint,2,opt,name=tid" json:"tid,omitempty"`
	SerialNumber uint32                     `protobuf:"varint,3,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	Type         ControlCommand_CommandType `protobuf:"varint,4,opt,name=type,enum=Report.ControlCommand_CommandType" json:"type,omitempty"`
	Paras        []*Param                   `protobuf:"bytes,5,rep,name=paras" json:"paras,omitempty"`
}

func (m *ControlCommand) Reset()                    { *m = ControlCommand{} }
func (m *ControlCommand) String() string            { return proto.CompactTextString(m) }
func (*ControlCommand) ProtoMessage()               {}
func (*ControlCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ControlCommand) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ControlCommand) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *ControlCommand) GetSerialNumber() uint32 {
	if m != nil {
		return m.SerialNumber
	}
	return 0
}

func (m *ControlCommand) GetType() ControlCommand_CommandType {
	if m != nil {
		return m.Type
	}
	return ControlCommand_CMT_INVALID
}

func (m *ControlCommand) GetParas() []*Param {
	if m != nil {
		return m.Paras
	}
	return nil
}

func init() {
	proto.RegisterType((*ControlCommand)(nil), "Report.ControlCommand")
	proto.RegisterEnum("Report.ControlCommand_CommandType", ControlCommand_CommandType_name, ControlCommand_CommandType_value)
}

func init() { proto.RegisterFile("control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0xa9, 0xdb, 0x8d, 0xcd, 0xa5, 0x9b, 0x79, 0xc6, 0x46, 0x46, 0x19, 0x64, 0x1d, 0x42,
	0x39, 0xa0, 0x1e, 0x3a, 0x40, 0x5c, 0x4d, 0x63, 0x46, 0xa4, 0x36, 0xf1, 0x6c, 0x77, 0x88, 0x53,
	0xd4, 0xd1, 0x1e, 0x2a, 0xad, 0x4d, 0x95, 0xb5, 0x87, 0xdd, 0xc2, 0x9b, 0x78, 0xb9, 0xf1, 0x7a,
	0x87, 0xcf, 0xc1, 0x87, 0x43, 0x69, 0xf0, 0x96, 0xa4, 0x9d, 0x38, 0xd5, 0xfa, 0xff, 0xfe, 0x3f,
	0xf7, 0x89, 0xad, 0x04, 0x57, 0x5e, 0x05, 0xa3, 0x49, 0x18, 0x9c, 0xd4, 0xc7, 0x61, 0x30, 0x09,
	0x60, 0x59, 0xf4, 0xc7, 0x41, 0x38, 0xb9, 0x55, 0x1e, 0x77, 0xc3, 0xee, 0x30, 0x09, 0x6b, 0x7f,
	0x56, 0xf1, 0x5a, 0x33, 0xa9, 0x35, 0x83, 0xe1, 0xb0, 0x3b, 0xea, 0x01, 0xe0, 0xd2, 0x74, 0x3a,
	0xe8, 0x19, 0x05, 0xb3, 0x60, 0xad, 0x8a, 0xd9, 0x1a, 0x08, 0x2e, 0x4e, 0x06, 0x3d, 0x03, 0x99,
	0x05, 0xab, 0x24, 0xe2, 0x25, 0xec, 0xe1, 0xca, 0x69, 0x3f, 0x1c, 0x74, 0x4f, 0xfc, 0xd1, 0x74,
	0x78, 0xdc, 0x0f, 0x8d, 0xa2, 0x59, 0xb0, 0x2a, 0xe2, 0x5a, 0x12, 0xba, 0xb3, 0x0c, 0x1e, 0xe3,
	0xd2, 0xe4, 0x6c, 0xdc, 0x37, 0x4a, 0x66, 0xc1, 0x5a, 0x6b, 0xd4, 0xea, 0xc9, 0x04, 0xf5, 0xec,
	0x1f, 0xd6, 0xff, 0xfd, 0xaa, 0xb3, 0x71, 0x5f, 0xcc, 0xfa, 0xb0, 0x87, 0x97, 0xe2, 0x21, 0x4f,
	0x8d, 0x25, 0xb3, 0x68, 0x95, 0x1b, 0x15, 0x2d, 0xf2, 0x78, 0x72, 0x91, 0xb0, 0xda, 0xeb, 0x15,
	0x5c, 0x4e, 0xa9, 0xb0, 0x8e, 0xcb, 0xcd, 0xb6, 0xf2, 0x1d, 0xf7, 0x88, 0xb6, 0x1c, 0x9b, 0x5c,
	0x81, 0x0d, 0xbc, 0x1e, 0x07, 0x82, 0x1d, 0xfa, 0x82, 0x49, 0x45, 0x85, 0x22, 0x45, 0xd8, 0xd4,
	0x21, 0x3f, 0x0f, 0xdf, 0x46, 0x08, 0xb6, 0xf1, 0xa6, 0xee, 0xda, 0x54, 0x51, 0xdf, 0xf6, 0x5e,
	0xb8, 0x2d, 0x8f, 0xda, 0xe4, 0x2a, 0x54, 0x35, 0xe2, 0x39, 0xf4, 0x21, 0x42, 0xb0, 0x85, 0x21,
	0xe3, 0x1d, 0x76, 0x98, 0x78, 0x49, 0x56, 0xc0, 0xd0, 0x39, 0x4f, 0xe7, 0x1f, 0x23, 0x04, 0x3b,
	0x78, 0x5b, 0x1b, 0x4f, 0xa9, 0x6a, 0x3e, 0xf7, 0xa9, 0x6d, 0xfb, 0x6d, 0xcf, 0x75, 0x94, 0x27,
	0xc8, 0x2a, 0xdc, 0xd5, 0x98, 0x2f, 0xc0, 0x9f, 0x22, 0x04, 0x55, 0x7c, 0x73, 0xde, 0xa7, 0x2d,
	0xc5, 0x04, 0xc1, 0xb0, 0xa3, 0x21, 0x9f, 0x83, 0x9f, 0x23, 0x04, 0xb7, 0xb1, 0x71, 0x7e, 0x22,
	0xb2, 0xb1, 0xdf, 0xf0, 0x0f, 0x98, 0xf2, 0x9b, 0x9e, 0xfb, 0xcc, 0x39, 0x20, 0xd7, 0xe1, 0x8e,
	0xa6, 0x7c, 0x9e, 0x7e, 0x59, 0x64, 0xcb, 0x0b, 0x0e, 0xf3, 0x76, 0x8a, 0x7e, 0xcd, 0x9e, 0x70,
	0xbc, 0x2f, 0xa7, 0x82, 0xb6, 0x15, 0x13, 0x92, 0x6c, 0xa4, 0x4f, 0x38, 0x8b, 0xbe, 0x65, 0x3d,
	0x99, 0x81, 0x37, 0xd2, 0x5e, 0x16, 0x7d, 0xcf, 0x4f, 0xfb, 0xf0, 0xc9, 0xa3, 0xf4, 0xd3, 0xec,
	0x66, 0xa7, 0xcd, 0xd1, 0x5f, 0x8b, 0xec, 0xd4, 0xd3, 0xd4, 0xe6, 0xed, 0x14, 0xfd, 0x9d, 0xbd,
	0xa3, 0x78, 0x5f, 0xc9, 0xc4, 0x11, 0x13, 0xf1, 0x5d, 0x08, 0x52, 0x4a, 0xdf, 0x51, 0x1e, 0xbe,
	0xcb, 0xba, 0x32, 0x87, 0x97, 0xd2, 0x6e, 0x1e, 0xbe, 0x8f, 0x10, 0xdc, 0xc3, 0xa6, 0x76, 0x95,
	0xa0, 0xae, 0xe4, 0x54, 0x30, 0x57, 0x25, 0xeb, 0xb6, 0x23, 0xa5, 0xe3, 0xb9, 0x64, 0x13, 0xee,
	0xeb, 0x16, 0xbf, 0xbc, 0xf5, 0x23, 0x42, 0xf0, 0x00, 0x5b, 0x17, 0xef, 0x4f, 0x8b, 0x51, 0xc9,
	0x2e, 0xef, 0x6f, 0x41, 0x5d, 0xb7, 0xf9, 0xff, 0xdb, 0x3f, 0x23, 0x04, 0x26, 0xae, 0xea, 0xdd,
	0x67, 0x2f, 0x87, 0x2f, 0xbc, 0x8e, 0x62, 0xc2, 0x97, 0x8a, 0xaa, 0x8e, 0x24, 0x11, 0x82, 0x5d,
	0xdd, 0xe0, 0x8b, 0x1b, 0x6f, 0xd0, 0xf1, 0xf2, 0xec, 0x2b, 0xb6, 0xff, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x29, 0xbc, 0x89, 0x8d, 0xeb, 0x04, 0x00, 0x00,
}
